### ISSUE TITLE
Update from 2.0.3 to 2.0.4 potential new bug

### ISSUE THREAD

**Issue by ktonon** [TheDeveloper/http-aws-es#36]
This is how I'm instantiating the client:

```javascript
const AWS = require('aws-sdk');

AWS.config.update({ region: 'ca-central-1' });

const AWS_ES = require('http-aws-es');
const elasticsearch = require('elasticsearch');

new elasticsearch.Client({
  host: 'https://***.ca-central-1.es.amazonaws.com:80/'
  log: 'trace'
  apiVersion: '5.3'
  connectionClass: AWS_ES,
});
```

With `2.0.3` of `http-aws-es` I get this trace:

```
Elasticsearch INFO: 2017-07-15T11:17:59Z
  Adding connection to https://***.es.amazonaws.com:80/

Elasticsearch DEBUG: 2017-07-15T11:17:59Z
  starting request {
    "method": "GET",
    "path": "/_cat/templates/some-template",
    "query": {
      "format": "json"
    }
  }

Elasticsearch TRACE: 2017-07-15T11:18:00Z
  -> GET https://***.es.amazonaws.com:80/_cat/templates/some-template?format=json

  <- 200
  [
    {
      "name": "some-template",
      "template": "some-template-*",
      "order": "1",
      "version": "1"
    }
  ]

Elasticsearch DEBUG: 2017-07-15T11:18:00Z
  Request complete
```

With `2.0.4` I get this trace:

```
Elasticsearch INFO: 2017-07-15T11:10:23Z
  Adding connection to https://***.ca-central-1.es.amazonaws.com:80/

Elasticsearch DEBUG: 2017-07-15T11:10:23Z
  starting request {
    "method": "GET",
    "path": "/_cat/templates/some-template",
    "query": {
      "format": "json"
    }
  }


Elasticsearch TRACE: 2017-07-15T11:10:23Z
  -> GET https://***.ca-central-1.es.amazonaws.com:80/_cat/templates/some-template?format=json

  <- 0


Elasticsearch ERROR: 2017-07-15T11:10:23Z
  Error: Request error, retrying
  GET https://***.ca-central-1.es.amazonaws.com:80/_cat/templates/some-template?format=json => write EPROTO 140737038898112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

      at Log.error (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpAmazonESConnector.<anonymous> (/Users/ktonon/repos/folio-service/node_modules/http-aws-es/node6.js:77:11)
      at ClientRequest.bound (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at ClientRequest.<anonymous> (/Users/ktonon/repos/folio-service/node_modules/aws-sdk/lib/http/node.js:89:19)
      at emitOne (events.js:101:20)
      at ClientRequest.emit (events.js:188:7)
      at TLSSocket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:188:7)

Elasticsearch TRACE: 2017-07-15T11:10:23Z
  -> GET https://***.ca-central-1.es.amazonaws.com:80/_cat/templates/some-template?format=json

  <- 0


Elasticsearch ERROR: 2017-07-15T11:10:23Z
  Error: Request error, retrying
  GET https://***.ca-central-1.es.amazonaws.com:80/_cat/templates/some-template?format=json => write EPROTO 140737038898112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

      at Log.error (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/src/lib/log.js:225:56)
      at checkRespForFailure (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/src/lib/transport.js:258:18)
      at HttpAmazonESConnector.<anonymous> (/Users/ktonon/repos/folio-service/node_modules/http-aws-es/node6.js:77:11)
      at ClientRequest.bound (/Users/ktonon/repos/folio-service/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
      at emitOne (events.js:101:20)
      at ClientRequest.emit (events.js:188:7)
      at TLSSocket.socketErrorListener (_http_client.js:310:9)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:188:7)
      at onwriteError (_stream_writable.js:346:10)

Elasticsearch TRACE: 2017-07-15T11:10:23Z
  -> HEAD https://***.ca-central-1.es.amazonaws.com:80/

  <- 0


Elasticsearch WARNING: 2017-07-15T11:10:23Z
  Unable to revive connection: https://***.ca-central-1.es.amazonaws.com:80/

Elasticsearch TRACE: 2017-07-15T11:10:23Z
  -> HEAD https://***.ca-central-1.es.amazonaws.com:80/

  <- 0


Elasticsearch WARNING: 2017-07-15T11:10:23Z
  Unable to revive connection: https://***.ca-central-1.es.amazonaws.com:80/

Elasticsearch WARNING: 2017-07-15T11:10:23Z
  No living connections

Elasticsearch WARNING: 2017-07-15T11:10:23Z
  No living connections
```

AFAIK nothing else changes between the two invocations, its just the version of `http-aws-es`.

Thanks!

**Comment by TheDeveloper** [comment]
Hi, thanks for the report.

Try dropping the :80 from your ES host url. We made a change where this is no longer needed.

**Comment by TheDeveloper** [comment]
@ktonon are you still seeing issues?

**Comment by ktonon** [comment]
@TheDeveloper yes, you are right. Dropping `:80` resolves the issue. Thanks! Sorry for the delayed response.
