### ISSUE TITLE
Support for node 7

### ISSUE THREAD

**Issue by flache** [TheDeveloper/http-aws-es#39]
When I try to run this module with node v.7.1.0 i get the following error:

```
[...]/node_modules/http-aws-es/node8.js:45
  async request(params, cb) {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([...]/node_modules/http-aws-es/index.js:8:20)
    at Module._compile (module.js:573:32)
```

This module seems to check only for even versions (<4, 4, 6) in the `index.js` file and automatically includes the version for node 8 for all other cases (i.e. node 5 and 7).

It would be very nice if there was support also for the non-LTS versions. Would it be a problem to change the version check into something like this?

```js
if (nodeMajor < 4) {
  module.exports = require('./legacy');
} else if (nodeMajor < 6) {
  module.exports = require('./node4');
} else if (nodeMajor < 8) {
  module.exports = require('./node6');
} else {
  module.exports = require('./node8');
}
```

**Comment by bradennapier** [comment]
Also running into this.  Top AWS Lambda uses Node 6 which this does not work with.

**Comment by flache** [comment]
thanks!
