### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by renehauck** [TheDeveloper/http-aws-es#43]
Hi,

after an update, I tried to test my source code. 
It all looked good, but a few tests suddenly fail each time with the "group" property, which is an string-array or the "latlng" which is a geo_point.

The response is:

```
Error: Authorization Exception
    at respond (/home/rene/Projekte/SmashoCore/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/home/rene/Projekte/SmashoCore/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at IncomingMessage.cleanUp (/home/rene/Projekte/SmashoCore/node_modules/http-aws-es/connector.js:60:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  status: 403,
  displayName: 'AuthorizationException',
  message: 'Authorization Exception',
  path: '/_bulk',
  query: { refresh: 'true' },
  body: '{"index":{"_index":"newsmasho","_type":"User","_id":"User_6v7dr8j92p3jer"}}\n{"__model_name":"User","__model_options":{"created":true},"email":"test3@test.de","name":"Rainer","latlng":{"lat":0,"lon":0},"createdAt":1508673246723,"ratingHistory":[],"watchList":[],"groups":["Antiquitäten und Sammler"],"favoriteList":[],"updatedAt":1508673246914}\n',
  statusCode: 403,
  response: '{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.
```

**Comment by TheDeveloper** [comment]
Thanks for the report! Fixed in 3.1.2
